meta:
  version: "0.1.0"
  purpose: "Rules help to assess design completeness and quality of generated specs"

# Core assessment framework
assessment_framework:
  required_sections:
    all_components:
      - section: "purpose"
        weight: 25
        critical: true
        description: "Clear problem statement"
        
      - section: "basic_interfaces"
        weight: 15
        critical: true
        description: "At least one interface defined"
        
      - section: "dependencies"
        weight: 10
        critical: false
        description: "Dependencies identified"
        
    storage_components:
      - section: "error_handling"
        weight: 15
        critical: true
        description: "Error scenarios handled"
        
      - section: "backup_strategy"
        weight: 10
        critical: true
        description: "Data protection plan"
        
      - section: "data_integrity"
        weight: 10
        critical: false
        description: "Corruption detection"
        
    ui_components:
      - section: "states"
        weight: 20
        critical: true
        description: "Component states defined"
        
      - section: "user_interactions"
        weight: 15
        critical: true
        description: "User flows specified"
        
      - section: "accessibility_notes"
        weight: 10
        critical: false
        description: "A11y considerations"
        
    api_components:
      - section: "error_codes"
        weight: 15
        critical: true
        description: "Error response codes"
        
      - section: "authentication"
        weight: 20
        critical: true
        description: "Auth mechanism defined"
        
      - section: "rate_limiting"
        weight: 10
        critical: false
        description: "Rate limiting strategy"
        
    ai_components:
      - section: "safety_guardrails"
        weight: 25
        critical: true
        description: "Safety measures defined"
        
      - section: "fallback_strategies"
        weight: 20
        critical: true
        description: "Fallback plans"
        
      - section: "cost_constraints"
        weight: 15
        critical: false
        description: "Cost management"

# Scoring algorithms
scoring_methods:
  simple_percentage:
    formula: "(answered_questions / total_questions) * 100"
    adjustments: []
    
  weighted_percentage:
    formula: "sum(question_weight * completion_score)"
    adjustments:
      - "critical_gap_penalty: -10 points per critical gap"
      - "completeness_bonus: +5 points if all sections complete"
      
  quality_adjusted:
    formula: "weighted_percentage * quality_multiplier"
    quality_factors:
      - "answer_specificity: vague answers reduce score"
      - "implementation_clarity: unclear specs reduce score"
      - "consistency: contradictory answers reduce score"

# Quality gates and thresholds
quality_gates:
  prototype_ready:
    minimum_score: 60
    required_sections: ["purpose", "basic_interfaces"]
    critical_gaps_allowed: 0
    
  production_ready:
    minimum_score: 80
    required_sections: ["purpose", "interfaces", "error_handling", "dependencies"]
    critical_gaps_allowed: 0
    
  enterprise_ready:
    minimum_score: 90
    required_sections: ["purpose", "interfaces", "error_handling", "dependencies", "observability", "security"]
    critical_gaps_allowed: 0

# Assessment output templates
report_templates:
  basic_report:
    sections:
      - "coverage_summary"
      - "critical_gaps"
      - "recommendations"
      
  detailed_report:
    sections:
      - "executive_summary"
      - "coverage_breakdown"
      - "gap_analysis"
      - "risk_assessment"
      - "improvement_roadmap"
      - "implementation_readiness"

# Penalty rules
penalty_rules:
  critical_gaps:
    storage_without_backup: -15
    ui_without_error_states: -10
    api_without_auth: -20
    ai_without_safety: -25
    
  consistency_issues:
    contradictory_requirements: -5
    missing_dependencies: -3
    unclear_interfaces: -2
    
  completeness_issues:
    vague_purpose: -5
    missing_success_criteria: -3
    undefined_error_handling: -4

# Bonus rules
bonus_rules:
  completeness_bonus:
    all_sections_complete: +5
    comprehensive_error_handling: +3
    detailed_observability: +2
    
  quality_bonus:
    specific_measurable_purpose: +2
    comprehensive_state_definition: +3
    clear_implementation_guidance: +2